/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package proj1.javafx.gradle;

import javafx.application.Application;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.PasswordField;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    public static void main(String[] args) {
    	launch(args);
    }

	@Override
	public void start(Stage primaryStage) throws Exception {
		primaryStage.setTitle("Tela de Login");
		
		// Componentes da tela de login.		
		Label usernameLabel = new Label("Nome de Usuário:");
		TextField usernameField = new TextField();
		
		Label passwordLabel = new Label("Senha:");
		PasswordField passwordField = new PasswordField();
		
		Button loginButton = new Button("Login");
		Label statusLabel = new Label();
		
		 // Evento de clique no botão de login.
		loginButton.setOnAction(e -> {
			String username = usernameField.getText();
			String password = passwordField.getText();
			
			// Verifica se o login é válido.
			if ("usuario".equals(username) && "senha123".equals(password)) {
				statusLabel.setText("Login Bem-Vindo!");
				statusLabel.setStyle("-fx-text-fill: #10793F;");
			} else {
				statusLabel.setText("Nome de usuário ou senha incorreta, tente novamente.");
				statusLabel.setStyle("-fx-text-fill: #f3212d;");
			}
		});
		
		// Aplicação de estilos aos elementos.
		usernameLabel.setStyle("-fx-text-fill: #18507a;");
		passwordLabel.setStyle("-fx-text-fill: #18507a;");
		loginButton.setStyle("-fx-background-color: #2196F3; -fx-text-fill: #fff;");
		statusLabel.setStyle("-fx-text-fill: #fff;");
		
		 // Layout da tela de login.
		BorderPane borderPane = new BorderPane();
		
		VBox loginVBox = new VBox(10);
		loginVBox.setPadding(new Insets(20, 20, 20, 20));
		loginVBox.setStyle("-fx-background-color: #f2f2f2;");
		loginVBox.getChildren().addAll(usernameLabel, usernameField, passwordLabel, passwordField, loginButton, statusLabel);
		borderPane.setCenter(loginVBox);
		
		// Título.
		Label bannerLabel = new Label("Bem-vindo à Aplicação");
		bannerLabel.setStyle("-fx-background-color: #f32196; -fx-padding: 15px 110px; -fx-text-fill: white;");
		borderPane.setTop(bannerLabel);
		
		Scene scene = new Scene(borderPane, 350, 250);
		primaryStage.setScene(scene);
		
		primaryStage.show();
	}
}